CREATE DATABASE inlock_games_dbFirst_Lucas
USE inlock_games_dbFirst_Lucas

CREATE TABLE Estudio
(
	IdEstudio UNIQUEIDENTIFIER PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
)

CREATE TABLE Jogo
(
	IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
	IdEstudio UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Estudio(IdEstudio),
	Nome VARCHAR(100) NOT NULL,
	Descricao VARCHAR(100) NOT NULL, 
	DataLancamento DATE NOT NULL,
	Valor SMALLMONEY NOT NULL
)

CREATE TABLE TiposUsuario
(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TiposUsuario(IdTipoUsuario),
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(100) NOT NULL
)

INSERT INTO Estudio
VALUES (NEWID(),'SENAI'), (NEWID(),'SESI'), (NEWID(),'SEBRAE')

SELECT *FROM Estudio

INSERT INTO Jogo
VALUES (NEWID(),'C4F82B65-8B8E-43E7-B07D-4A05EB7D70D7','PING PONG', 'JOGO LEGAL', '2023-01-01',500),
	   (NEWID(),'C4F82B65-8B8E-43E7-B07D-4A05EB7D70D7','JUCAMOM', 'CAÇA POKEMOM', '2022-03-23',2.99)

SELECT *FROM Jogo

INSERT INTO TiposUsuario
VALUES (NEWID(),'administrador'),(NEWID(),'comum')

SELECT *FROM TiposUsuario

INSERT INTO Usuario
VALUES (NEWID(),'B1A725E2-388D-4609-A86F-18EDAF44C3E1','adm@adm.com','admin'),
	   (NEWID(),'197F09FB-FFC4-4167-9546-D9A2589CA157','comum@comum.com','comum')

SELECT *FROM Usuario